platform: linux
image_resource:
  type: docker-image
  source: {repository: cfmobile/ginkgo}
inputs:
- name: yml2env
  path: gopath/src/github.com/EngineerBetter/yml2env
run:
  path: gopath/src/github.com/EngineerBetter/yml2env/ci/tasks/release/run.sh
outputs:
- name: build