---
jobs:
- name: test
  public: true
  plan:
  - get: yml2env
    trigger: true
  - task: test
    file: yml2env/ci/tasks/test/task.yml

resources:
- name: yml2env
  type: git
  source:
    uri: https://github.com/EngineerBetter/yml2env.git
    branch: master